export const audio = [
  {
    id: 2001,
    name: 'JBL PARTYBOX 310, Black',
    price: 10000,
    credit: 1000,
    cashback: 1200,
    model: 'Partybox 310',
    color: 'Black',
    weight: 17420,
    popularity: 32,
    manufacturer: 'JBL',
    imageUrl:
      'https://darwin.md/images/product/2020/12/jbl_partybox_310_black_1.webp',
    type: 'audio',
    segment: 'Party Speakers',
    link: 'jbl-partybox-310-black',
    colors: ['black'],
    chargingTime: 3.5,
    workingTimeHours: 18,
    bluetooth: 5.1,
    power: 240,
    workingDistance: 10,
    audioFrequency: '50 Hz - 20 kHz',
    audioFormats: ['mp3', 'wma', 'wav'],
    usbConnectors: 1
  },
  {
    id: 2002,
    name: 'Soundbar JBL 2.1 Depp Bass with Wireless Subwoofer, Black',
    price: 6500,
    credit: 650,
    cashback: 800,
    model: 'Bar 2.1',
    color: 'Black',
    weight: 1900,
    popularity: 21,
    manufacturer: 'JBL',
    imageUrl: 'https://darwin.md/images/product/2020/12/jbl_bar_2_1_1d.webp',
    type: 'audio',
    segment: 'Soundbar',
    link: 'soundbar-jbl-bar-2-1-with-wireless-subwoofer-black',
    colors: ['black'],
    chargingTime: 3.5,
    workingTimeHours: 18,
    bluetooth: 5.0,
    power: 300,
    workingDistance: 10,
    audioFrequency: '40 Hz - 20 kHz',
    audioFormats: ['mp3', 'wma', 'wav']
  },
  {
    id: 2003,
    name: 'Sven PS-750, Black',
    price: 2900,
    credit: 290,
    cashback: 350,
    model: 'PS-750',
    color: 'Black',
    weight: 5200,
    popularity: 37,
    manufacturer: 'Sven',
    imageUrl:
      'https://darwin.md/images/product/2020/12/sven_ps_750_black_1.webp',
    type: 'audio',
    segment: 'Party Speakers',
    link: 'sven-ps-750-black',
    colors: ['black'],
    chargingTime: 2,
    workingTimeHours: 10,
    bluetooth: 5.0,
    power: 80,
    workingDistance: 10,
    audioFrequency: '45 Hz - 20 kHz',
    audioFormats: ['mp3', 'wma', 'wav'],
    batteryCapacity: 8800
  },
  {
    id: 2004,
    name: 'Sven PS-520, Black',
    price: 1900,
    credit: 190,
    cashback: 250,
    model: 'PS-520',
    color: 'Black',
    weight: 2850,
    popularity: 41,
    manufacturer: 'Sven',
    imageUrl:
      'https://darwin.md/images/product/2020/09/sven_ps_520_black_1.webp',
    type: 'audio',
    segment: 'Party Speakers',
    link: 'sven-ps-520-black',
    colors: ['black'],
    bluetooth: 5.0,
    power: 36,
    workingDistance: 10,
    audioFrequency: '80 Hz - 20 kHz',
    audioFormats: ['mp3', 'wma', 'wav'],
    batteryCapacity: 4000,
    usbConnectors: 1
  },
  {
    id: 2005,
    name: 'HyperX Cloud Alpha S (HX-HSCAS), Black Blue',
    price: 2800,
    credit: 280,
    cashback: 400,
    model: 'Alpha S (HX-HSCAS)',
    color: 'Blue',
    weight: 310,
    popularity: 70,
    manufacturer: 'HyperX',
    imageUrl:
      'https://darwin.md/images/product/2021/02/coud_alpha_s_black_2d.webp',
    type: 'audio',
    segment: 'Gaming Headphones',
    link: 'hyperx-cloud-alpha-s-hx-hscas-blue',
    colors: ['blue', 'black'],
    audioFrequency: '13 Hz - 27000 Hz',
    interface: ['USB', '3.5 mm jack'],
    microphone: true,
    connectionType: 'wired',
    wireLength: 1.8
  },
  {
    id: 2006,
    name: 'HyperX Cloud Alpha S (HX-HSCAS), Black',
    price: 2800,
    credit: 280,
    cashback: 400,
    model: 'Alpha S (HX-HSCAS)',
    color: 'Black',
    weight: 310,
    popularity: 72,
    manufacturer: 'HyperX',
    imageUrl:
      'https://darwin.md/images/product/2021/05/hyperx_cloud_alpha_s_black5.webp',
    type: 'audio',
    segment: 'Gaming Headphones',
    link: 'hyperx-cloud-alpha-s-hx-hscas-black',
    colors: ['blue', 'black'],
    audioFrequency: '13 Hz - 27000 Hz',
    interface: ['USB', '3.5 mm jack'],
    microphone: true,
    connectionType: 'wired',
    wireLength: 1.8
  },
  {
    id: 2007,
    name: 'Microfon Razer Seiren Mini (RZ19-03450100-R3M1), Black',
    price: 1400,
    credit: 140,
    cashback: 200,
    model: 'Seiren Mini (RZ19-03450100-R3M1)',
    color: 'Black',
    weight: 550,
    popularity: 11,
    manufacturer: 'Razer',
    imageUrl:
      'https://darwin.md/images/product/2020/12/razer_portable_mini_black1.webp',
    type: 'audio',
    segment: 'Microphone',
    link: 'razer-seiren-mini-black-rz19',
    colors: ['black'],
    audioFrequency: '20 Hz - 20 kHz',
    interface: ['USB'],
    sensitivity: 110
  },
  {
    id: 2008,
    name: 'Microfon Gaming HyperX QuadCast S, Black',
    price: 3400,
    credit: 340,
    cashback: 400,
    model: 'QuadCast S',
    color: 'Black',
    weight: 710,
    popularity: 65,
    manufacturer: 'HyperX',
    imageUrl:
      'https://darwin.md/images/product/2020/11/huperx_quadcast_s_black_1.webp',
    type: 'audio',
    segment: 'Microphone',
    link: 'hyperx-quadcast-s-black',
    colors: ['black'],
    audioFrequency: '20 Hz - 20 kHz',
    interface: ['USB Type-C', 'RGB'],
    sensitivity: 36,
    impendance: 32,
    connectionType: 'wired',
    wireLength: 3
  },
  {
    id: 2009,
    name: 'Microfon Gaming HyperX QuadCast, Black',
    price: 2600,
    credit: 260,
    cashback: 300,
    model: 'QuadCast',
    color: 'Black',
    weight: 710,
    popularity: 90,
    manufacturer: 'HyperX',
    imageUrl:
      'https://darwin.md/images/product/2020/10/hyper_x_quadcast_black_1.webp',
    type: 'audio',
    segment: 'Microphone',
    link: 'hyperx-quadcast-black',
    colors: ['black'],
    audioFrequency: '20 Hz - 20 kHz',
    interface: ['miniUSB'],
    sensitivity: 36,
    impendance: 32,
    connectionType: 'wired',
    wireLength: 3
  },
  {
    id: 2010,
    name: 'Microfon Gaming Razer Seiren X, Black',
    price: 2500,
    credit: 250,
    cashback: 250,
    model: 'Seiren X',
    color: 'Black',
    weight: 383,
    popularity: 87,
    manufacturer: 'Razer',
    imageUrl:
      'https://darwin.md/images/product/2021/02/razer_seiren_x_black_2.webp',
    type: 'audio',
    segment: 'Microphone',
    link: 'gaming-razer-seiren-x-black',
    colors: ['black'],
    audioFrequency: '20 Hz - 20 kHz',
    interface: ['USB'],
    sensitivity: 110
  },
  {
    id: 2011,
    name: 'HyperX Cloud Alpha (HX-HSCA), Black Red',
    price: 2400,
    credit: 240,
    cashback: 250,
    model: 'Alpha (HX-HSCA)',
    color: 'Red',
    weight: 321,
    popularity: 88,
    manufacturer: 'HyperX',
    imageUrl:
      'https://darwin.md/images/product/2020/12/cloud_alpha_black_red_1.webp',
    type: 'audio',
    segment: 'Gaming Headphones',
    link: 'hyperx-cloud-alpha-hsca-black-red',
    colors: ['black'],
    audioFrequency: '13 Hz - 27000 Hz',
    interface: ['USB', '3.5 mm jack'],
    microphone: true,
    connectionType: 'wired',
    wireLength: 1.8
  },
  {
    id: 2012,
    name: 'Razer Kraken Tournament Edition, Green',
    price: 2300,
    credit: 230,
    cashback: 250,
    model: 'Kraken Tournament Edition',
    color: 'Green',
    weight: 322,
    popularity: 85,
    manufacturer: 'Razer',
    imageUrl:
      'https://darwin.md/images/product/2021/01/razer_kraken_tournament_edition_green_1.webp',
    type: 'audio',
    segment: 'Gaming Headphones',
    link: 'gaming-razer-kraken-tournament-edition-green',
    colors: ['green', 'black'],
    audioFrequency: '12 Hz - 28000 Hz',
    interface: ['USB', '3.5 mm jack'],
    microphone: true,
    connectionType: 'wired',
    wireLength: 1.3
  },
  {
    id: 2013,
    name: 'Razer Kraken Tournament Edition, Black',
    price: 2300,
    credit: 230,
    cashback: 250,
    model: 'Kraken Tournament Edition',
    color: 'Black',
    weight: 322,
    popularity: 81,
    manufacturer: 'Razer',
    imageUrl:
      'https://darwin.md/images/product/2021/03/kraken_tournament_edition_black_1d.webp',
    type: 'audio',
    segment: 'Gaming Headphones',
    link: 'gaming-razer-kraken-tournament-edition-black',
    colors: ['green', 'black'],
    audioFrequency: '12 Hz - 28000 Hz',
    interface: ['USB', '3.5 mm jack'],
    microphone: true,
    connectionType: 'wired',
    wireLength: 1.3
  }
];
