export const gadgets = [
  {
    id: 1001,
    name: 'Xiaomi Mi Smart Band 5, Black',
    price: 700,
    credit: 70,
    cashback: 80,
    model: 'Mi Band 5',
    color: 'Black',
    weight: 12,
    popularity: 99,
    manufacturer: 'Xiaomi',
    imageUrl:
      'https://darwin.md/images/product/2020/07/mi_smart_band_5_black_1.webp',
    type: 'gadgets',
    segment: 'Smart Watch',
    link: 'mi-band-5-xiaomi-black',
    colors: ['black'],
    resolution: '126 x 294',
    display: '1.1"',
    displayType: 'AMOLED',
    touchScreen: true,
    chargingTime: 2,
    workingTimeDays: 14,
    batteryCapacity: 125,
    bluetooth: 5.0
  },
  {
    id: 1002,
    name: 'Xiaomi Mi Smart Band 6, Black',
    price: 1100,
    credit: 110,
    cashback: 130,
    model: 'Mi Band 6',
    color: 'Black',
    weight: 13,
    popularity: 97,
    manufacturer: 'Xiaomi',
    imageUrl:
      'https://darwin.md/images/product/2021/08/darwin-fitness-traker-xiaomi-mi-band-6-black-092.webp',
    type: 'gadgets',
    segment: 'Smart Watch',
    link: 'mi-smart-band-6-xiaomi-black',
    colors: ['black'],
    resolution: '152 x 486',
    display: '1.56"',
    displayType: 'AMOLED',
    touchScreen: true,
    chargingTime: 2,
    workingTimeDays: 14,
    batteryCapacity: 125,
    bluetooth: 5.0
  },
  {
    id: 1003,
    name: 'Sony PlayStation 5, White',
    price: 14000,
    credit: 1400,
    cashback: 1500,
    model: 'PlayStation 5',
    color: 'White',
    weight: 4500,
    popularity: 100,
    manufacturer: 'Sony',
    imageUrl:
      'https://darwin.md/images/product/2021/09/consola-pentru-jocuri-sony-playstation-5-digital-edition-white-011.webp',
    type: 'gadgets',
    link: 'sony-playstation-5-white',
    colors: ['white'],
    chipset: 'AMD Ryzen Zen 2',
    cores: 8,
    chipsetFrequency: '3500 MHz',
    hardDrive: 825,
    memory: 16,
    videoCard: 'AMD Radeon RDNA 2',
    bluetooth: 5.1
  },
  {
    id: 1004,
    name: 'Apple Watch SE 44mm, Space Gray / Black',
    price: 7600,
    credit: 760,
    cashback: 900,
    model: 'Watch SE',
    color: 'Space Gray',
    weight: 36,
    popularity: 95,
    manufacturer: 'Apple',
    imageUrl:
      'https://darwin.md/images/product/2020/09/space_gray-aluminium_case_with_black_sport_band_mydt2_1.webp',
    type: 'gadgets',
    segment: 'Smart Watch',
    link: 'watch-se-apple-44mm-32-gb-gray',
    colors: ['gray', 'silver', 'gold'],
    resolution: '324 x 394',
    display: '1.56"',
    displayType: 'Retina LTPO OLED',
    touchScreen: true,
    workingTimeHours: 18,
    bluetooth: 5.0,
    hardDrive: 32
  },
  {
    id: 1005,
    name: 'Apple Watch SE 44mm, Silver / White',
    price: 7600,
    credit: 760,
    cashback: 900,
    model: 'Watch SE',
    color: 'Silver',
    weight: 36,
    popularity: 16,
    manufacturer: 'Apple',
    imageUrl:
      'https://darwin.md/images/product/2020/09/apple_watch_se_44mm_silver_aluminium_case_with_white_sport_band_1.webp',
    type: 'gadgets',
    segment: 'Smart Watch',
    link: 'watch-se-apple-44mm-32-gb-silver',
    colors: ['gray', 'silver', 'gold'],
    resolution: '324 x 394',
    display: '1.56"',
    displayType: 'Retina LTPO OLED',
    touchScreen: true,
    workingTimeHours: 18,
    bluetooth: 5.0,
    hardDrive: 32
  },
  {
    id: 1006,
    name: 'Apple Watch SE 44mm, Gold / Pink Sand',
    price: 7600,
    credit: 760,
    cashback: 900,
    model: 'Watch SE',
    color: 'Gold',
    weight: 36,
    popularity: 95,
    manufacturer: 'Apple',
    imageUrl:
      'https://darwin.md/images/product/2020/09/apple_watch_se_gold_aluminum_sport-band_pink_sand_1-200917021532-darwin.webp',
    type: 'gadgets',
    segment: 'Smart Watch',
    link: 'watch-se-apple-44mm-32-gb-gold',
    colors: ['gray', 'silver', 'gold'],
    resolution: '324 x 394',
    display: '1.56"',
    displayType: 'Retina LTPO OLED',
    touchScreen: true,
    workingTimeHours: 18,
    bluetooth: 5.0,
    hardDrive: 32
  },
  {
    id: 1007,
    name: 'Xiaomi Smartwatch Amazfit Bip (A1608), Onyx Black',
    price: 1200,
    credit: 120,
    cashback: 140,
    model: 'Amazfit Bip (A1608)',
    color: 'Onyx Black',
    weight: 32,
    popularity: 61,
    manufacturer: 'Xiaomi',
    imageUrl:
      'https://darwin.md/images/product/2021/03/xiaomi_amazfit_black_1.webp',
    type: 'gadgets',
    segment: 'Smart Watch',
    link: 'xiaomi-smartwatch-amazfit-bip-a1608-onyx-black',
    colors: ['black'],
    resolution: '176 x 176 px',
    display: '1.28"',
    displayType: 'AMOLED',
    touchScreen: true,
    chargingTime: 2.5,
    workingTimeHours: 1080,
    batteryCapacity: 190,
    bluetooth: 4.0
  },
  {
    id: 1008,
    name: 'Xiaomi Amazfit GTS, Black',
    price: 2100,
    credit: 210,
    cashback: 250,
    model: 'Amazfit GTS (A1914)',
    color: 'Obsidian Black',
    weight: 25,
    popularity: 93,
    manufacturer: 'Xiaomi',
    imageUrl:
      'https://darwin.md/images/product/2021/02/amazfit_gts_black_1d.webp',
    type: 'gadgets',
    segment: 'Smart Watch',
    link: 'xiaomi-amazfit-gts-obsidian-black',
    colors: ['black', 'pink', 'blue', 'orange', 'gray'],
    resolution: '348 x 442',
    display: '1.65"',
    displayType: 'AMOLED',
    touchScreen: true,
    chargingTime: 2,
    workingTimeDays: 46,
    batteryCapacity: 220,
    bluetooth: 5.0
  },
  {
    id: 1009,
    name: 'Xiaomi Amazfit GTS, Pink',
    price: 2100,
    credit: 210,
    cashback: 250,
    model: 'Amazfit GTS (A1914)',
    color: 'Pink',
    weight: 25,
    popularity: 58,
    manufacturer: 'Xiaomi',
    imageUrl:
      'https://darwin.md/images/product/2021/02/amazfit_gts_pink_1d.webp',
    type: 'gadgets',
    segment: 'Smart Watch',
    link: 'xiaomi-amazfit-gts-obsidian-pink',
    colors: ['black', 'pink', 'blue', 'orange', 'gray'],
    resolution: '348 x 442',
    display: '1.65"',
    displayType: 'AMOLED',
    touchScreen: true,
    chargingTime: 2,
    workingTimeDays: 46,
    batteryCapacity: 220,
    bluetooth: 5.0
  },
  {
    id: 1010,
    name: 'Xiaomi Amazfit GTS, Blue',
    price: 2100,
    credit: 210,
    cashback: 250,
    model: 'Amazfit GTS (A1914)',
    color: 'Blue',
    weight: 25,
    popularity: 94,
    manufacturer: 'Xiaomi',
    imageUrl:
      'https://darwin.md/images/product/2021/02/amazfit_gts_blue_1d.webp',
    type: 'gadgets',
    segment: 'Smart Watch',
    link: 'xiaomi-amazfit-gts-obsidian-blue',
    colors: ['black', 'pink', 'blue', 'orange', 'gray'],
    resolution: '348 x 442',
    display: '1.65"',
    displayType: 'AMOLED',
    touchScreen: true,
    chargingTime: 2,
    workingTimeDays: 46,
    batteryCapacity: 220,
    bluetooth: 5.0
  },
  {
    id: 1011,
    name: 'Xiaomi Amazfit GTS, Orange',
    price: 2100,
    credit: 210,
    cashback: 250,
    model: 'Amazfit GTS (A1914)',
    color: 'Orange',
    weight: 25,
    popularity: 31,
    manufacturer: 'Xiaomi',
    imageUrl:
      'https://darwin.md/images/product/2021/02/amazfit_gts_orange_1d.webp',
    type: 'gadgets',
    segment: 'Smart Watch',
    link: 'xiaomi-amazfit-gts-obsidian-orange',
    colors: ['black', 'pink', 'blue', 'orange', 'gray'],
    resolution: '348 x 442',
    display: '1.65"',
    displayType: 'AMOLED',
    touchScreen: true,
    chargingTime: 2,
    workingTimeDays: 46,
    batteryCapacity: 220,
    bluetooth: 5.0
  },
  {
    id: 1012,
    name: 'Xiaomi Amazfit GTS, Gray',
    price: 2100,
    credit: 210,
    cashback: 250,
    model: 'Amazfit GTS (A1914)',
    color: 'Gray',
    weight: 25,
    popularity: 44,
    manufacturer: 'Xiaomi',
    imageUrl:
      'https://darwin.md/images/product/2021/02/amazfit_gts_gray_1d.webp',
    type: 'gadgets',
    segment: 'Smart Watch',
    link: 'xiaomi-amazfit-gts-obsidian-gray',
    colors: ['black', 'pink', 'blue', 'orange', 'gray'],
    resolution: '348 x 442',
    display: '1.65"',
    displayType: 'AMOLED',
    touchScreen: true,
    chargingTime: 2,
    workingTimeDays: 46,
    batteryCapacity: 220,
    bluetooth: 5.0
  },
  {
    id: 1013,
    name: 'Action Camera GoPro Hero 8, Black',
    price: 8700,
    credit: 870,
    cashback: 900,
    model: 'Hero 8',
    color: 'Black',
    weight: 126,
    popularity: 67,
    manufacturer: 'GoPro',
    imageUrl: 'https://darwin.md/images/product/2021/02/hero_8_black_1.webp',
    type: 'gadgets',
    segment: 'Action Camera',
    link: 'gopro-hero-8-black',
    colors: ['black'],
    resolution: '3840 x 2160',
    display: '1.65"',
    displayType: 'AMOLED',
    touchScreen: true,
    batteryCapacity: 1220,
    camera: 12
  },
  {
    id: 1014,
    name: 'Action Camera GoPro Hero 9, Black',
    price: 11000,
    credit: 1100,
    cashback: 1200,
    model: 'Hero 9',
    color: 'Black',
    weight: 158,
    popularity: 78,
    manufacturer: 'GoPro',
    imageUrl:
      'https://darwin.md/images/product/2021/01/go_pro_hero_9_black_1.webp',
    type: 'gadgets',
    segment: 'Action Camera',
    link: 'gopro-hero-9-black',
    colors: ['black'],
    resolution: '5120 x 2880',
    display: '2.27"',
    displayType: 'LCD',
    interface: ['USB Type C', 'microHDMI'],
    touchScreen: true,
    batteryCapacity: 1720,
    camera: 20,
    bluetooth: 5.1,
    microphone: true
  },
  {
    id: 1015,
    name: 'Samsung Galaxy Watch Active 2 44mm (R820), Aqua Black',
    price: 4800,
    credit: 480,
    cashback: 500,
    model: 'Active 2 44mm (R820)',
    color: 'Aqua Black',
    weight: 30,
    popularity: 61,
    manufacturer: 'Samsung',
    imageUrl:
      'https://darwin.md/images/product/2020/11/galaxy_watch_active2_aqua_black1.webp',
    type: 'gadgets',
    segment: 'Smart Watch',
    link: 'samsung-galaxy-watch-active-2-44mm-r820-black',
    colors: ['black', 'silver', 'pink'],
    resolution: '360 x 360',
    display: '1.4"',
    displayType: 'AMOLED',
    touchScreen: true,
    batteryCapacity: 340,
    bluetooth: 5.0
  },
  {
    id: 1016,
    name: 'Samsung Galaxy Watch Active 2 44mm (R820), Silver',
    price: 4800,
    credit: 480,
    cashback: 500,
    model: 'Active 2 44mm (R820)',
    color: 'Silver',
    weight: 30,
    popularity: 13,
    manufacturer: 'Samsung',
    imageUrl:
      'https://darwin.md/images/product/2020/11/galaxy_watch_active2_silver1.webp',
    type: 'gadgets',
    segment: 'Smart Watch',
    link: 'samsung-galaxy-watch-active-2-44mm-r820-silver',
    colors: ['black', 'silver', 'pink'],
    resolution: '360 x 360',
    display: '1.4"',
    displayType: 'AMOLED',
    touchScreen: true,
    batteryCapacity: 340,
    bluetooth: 5.0
  },
  {
    id: 1017,
    name: 'Samsung Galaxy Watch Active 2 44mm (R820), Pink',
    price: 4800,
    credit: 480,
    cashback: 500,
    model: 'Active 2 44mm (R820)',
    color: 'Pink',
    weight: 30,
    popularity: 17,
    manufacturer: 'Samsung',
    imageUrl:
      'https://darwin.md/images/product/2020/11/galaxy_watch_active2_gold_rose1.webp',
    type: 'gadgets',
    segment: 'Smart Watch',
    link: 'samsung-galaxy-watch-active-2-44mm-r820-pink',
    colors: ['black', 'silver', 'pink'],
    resolution: '360 x 360',
    display: '1.4"',
    displayType: 'AMOLED',
    touchScreen: true,
    batteryCapacity: 340,
    bluetooth: 5.0
  }
];
