export const gadgets = [
  {
    id: 1001,
    name: 'Xiaomi Mi Smart Band 5, Black',
    price: 700,
    credit: 70,
    cashback: 80,
    model: 'Mi Band 5',
    color: 'Black',
    weight: 12,
    popularity: 99,
    manufacturer: 'Xiaomi',
    imageUrl:
      'https://darwin.md/images/product/2020/07/mi_smart_band_5_black_1.webp',
    type: 'gadgets',
    segment: 'Smart Watch',
    link: 'mi-band-5-xiaomi-black',
    colors: ['black'],
    resolution: '126 x 294',
    display: '1.1"',
    displayType: 'AMOLED',
    touchScreen: true,
    chargingTime: 2,
    workingTimeDays: 14,
    batteryCapacity: 125,
    bluetooth: 5.0
  },
  {
    id: 1002,
    name: 'JBL PARTYBOX 310, Black',
    price: 10000,
    credit: 1000,
    cashback: 1200,
    model: 'Partybox 310',
    color: 'Black',
    weight: 17420,
    popularity: 92,
    manufacturer: 'JBL',
    imageUrl:
      'https://darwin.md/images/product/2020/12/jbl_partybox_310_black_1.webp',
    type: 'gadgets',
    segment: 'Party Speakers',
    link: 'jbl-partybox-310-black',
    colors: ['black'],
    chargingTime: 3.5,
    workingTimeHours: 18,
    bluetooth: 5.1,
    power: 240,
    workingDistance: 10,
    audioFrequency: '50 Hz - 20 kHz',
    audioFormats: ['mp3', 'wma', 'wav'],
    usbConnectors: 1
  },
  {
    id: 1003,
    name: 'Sony PlayStation 5, White',
    price: 14000,
    credit: 1400,
    cashback: 1500,
    model: 'PlayStation 5',
    color: 'White',
    weight: 4500,
    popularity: 100,
    manufacturer: 'Sony',
    imageUrl:
      'https://darwin.md/images/product/2020/10/sony_playstation_5_white_2.webp',
    type: 'gadgets',
    link: 'sony-playstation-5-white',
    colors: ['white'],
    chipset: 'AMD Ryzen Zen 2',
    cores: 8,
    chipsetFrequency: '3500 MHz',
    hardDrive: 825,
    memory: 16,
    videoCard: 'AMD Radeon RDNA 2',
    bluetooth: 5.1
  }
];
