export const personalTransport = [
  {
    id: 4001,
    name: 'Bicycle Forward Flash 26 17 White',
    price: 5500,
    credit: 550,
    cashback: 600,
    model: 'Flash 26 17',
    color: 'White',
    popularity: 98,
    manufacturer: 'Forward',
    imageUrl:
      'https://darwin.md/images/product/2021/07/darwin-bicicleta-forward-flash-26-17-white-07.webp',
    type: 'personal-transport',
    segment: 'Mountain Bike',
    link: 'forward-flash-26-17-white',
    colors: ['white'],
    releaseDate: 2021,
    wheelDiameter: 26,
    speedsNumber: 21,
    brakeType: 'Disc(mecanic)',
    rimMaterial: 'aluminium',
    frameMaterial: 'steel',
    frameDiameter: 17
  },
  {
    id: 4002,
    name: 'Bicycle Forward Hardi 26 17 Gray',
    price: 5200,
    credit: 520,
    cashback: 600,
    model: 'Hardi 26 17',
    color: 'Gray',
    popularity: 95,
    manufacturer: 'Forward',
    imageUrl:
      'https://darwin.md/images/product/2021/07/darwin-bicicleta-forward-hardi-26-17-gray-010.webp',
    type: 'personal-transport',
    segment: 'Mountain Bike',
    link: 'forward-hardi-26-17-gray',
    colors: ['gray'],
    releaseDate: 2021,
    wheelDiameter: 26,
    speedsNumber: 21,
    brakeType: 'Disc(mecanic)',
    rimMaterial: 'aluminium',
    frameMaterial: 'aluminium',
    frameDiameter: 17
  },
  {
    id: 4003,
    name: 'Bicycle Forward Sporting 27.5 19 Green',
    price: 4800,
    credit: 480,
    cashback: 500,
    model: 'Sporting 27.5 19',
    color: 'Green',
    popularity: 97,
    manufacturer: 'Forward',
    imageUrl:
      'https://darwin.md/images/product/2021/07/darwin-bicicleta-forward-sporting-275-19-green-062.webp',
    type: 'personal-transport',
    segment: 'Mountain Bike',
    link: 'forward-sporting-27.5-19-green',
    colors: ['green'],
    releaseDate: 2021,
    wheelDiameter: 27.5,
    speedsNumber: 21,
    brakeType: 'Disc(mecanic)',
    rimMaterial: 'aluminium',
    frameMaterial: 'steel',
    frameDiameter: 19
  },
  {
    id: 4004,
    name: 'Kick Scooter Xiaomi Mi PRO 2 Black',
    price: 11000,
    credit: 1100,
    cashback: 1200,
    model: 'Mi Pro 2',
    color: 'Black',
    weight: 14200,
    popularity: 90,
    manufacturer: 'Xiaomi',
    imageUrl:
      'https://darwin.md/images/product/2021/06/darwin-trotineta-electrica-xiaomi-mi-pro-2-black-fbc4025gl-0.webp',
    type: 'personal-transport',
    segment: 'Kick Scooter',
    link: 'xiaomi-mijia-pro-2-black',
    colors: ['black'],
    supportedWeight: 100,
    wheelDiameter: 8.5,
    maxSpeed: 25,
    power: 300,
    brakeType: 'Disc',
    material: 'aluminium',
    chargingTime: 9,
    batteryCapacity: 12800
  }
];
