export const personalTransport = [
  {
    id: 4001,
    name: 'Bicycle Forward Flash 26 17 White',
    price: 5500,
    credit: 550,
    cashback: 600,
    model: 'Flash 26 17',
    color: 'White',
    popularity: 98,
    manufacturer: 'Forward',
    imageUrl:
      'https://darwin.md/images/product/2021/07/darwin-bicicleta-forward-flash-26-17-white-07.webp',
    type: 'personal-transport',
    segment: 'Mountain Bike',
    link: 'forward-flash-26-17-white',
    colors: ['white'],
    releaseDate: 2021,
    wheelDiameter: 26,
    speedsNumber: 21,
    brakeType: 'Disc(mecanic)',
    rimMaterial: 'aluminium',
    frameMaterial: 'steel',
    frameDiameter: 17
  },
  {
    id: 4002,
    name: 'Bicycle Forward Hardi 26 17 Gray',
    price: 5200,
    credit: 520,
    cashback: 600,
    model: 'Hardi 26 17',
    color: 'Gray',
    popularity: 95,
    manufacturer: 'Forward',
    imageUrl:
      'https://darwin.md/images/product/2021/07/darwin-bicicleta-forward-hardi-26-17-gray-010.webp',
    type: 'personal-transport',
    segment: 'Mountain Bike',
    link: 'forward-hardi-26-17-gray',
    colors: ['gray'],
    releaseDate: 2021,
    wheelDiameter: 26,
    speedsNumber: 21,
    brakeType: 'Disc(mecanic)',
    rimMaterial: 'aluminium',
    frameMaterial: 'aluminium',
    frameDiameter: 17
  },
  {
    id: 4003,
    name: 'Bicycle Forward Sporting 27.5 19 Green',
    price: 4800,
    credit: 480,
    cashback: 500,
    model: 'Sporting 27.5 19',
    color: 'Green',
    popularity: 97,
    manufacturer: 'Forward',
    imageUrl:
      'https://darwin.md/images/product/2021/07/darwin-bicicleta-forward-sporting-275-19-green-062.webp',
    type: 'personal-transport',
    segment: 'Mountain Bike',
    link: 'forward-sporting-27.5-19-green',
    colors: ['green'],
    releaseDate: 2021,
    wheelDiameter: 27.5,
    speedsNumber: 21,
    brakeType: 'Disc(mecanic)',
    rimMaterial: 'aluminium',
    frameMaterial: 'steel',
    frameDiameter: 19
  },
  {
    id: 4004,
    name: 'Kick Scooter Xiaomi Mi PRO 2 Black',
    price: 11000,
    credit: 1100,
    cashback: 1200,
    model: 'Mi Pro 2',
    color: 'Black',
    weight: 14200,
    popularity: 90,
    manufacturer: 'Xiaomi',
    imageUrl:
      'https://darwin.md/images/product/2021/06/darwin-trotineta-electrica-xiaomi-mi-pro-2-black-fbc4025gl-0.webp',
    type: 'personal-transport',
    segment: 'Kick Scooter',
    link: 'xiaomi-mijia-pro-2-black',
    colors: ['black'],
    supportedWeight: 100,
    wheelDiameter: 8.5,
    maxSpeed: 25,
    power: 300,
    brakeType: 'Disc',
    material: 'aluminium',
    chargingTime: 9,
    batteryCapacity: 12800,
    electricRange: 30
  },
  {
    id: 4005,
    name: 'Electric Scooter AIMA TIGER X6 (1800 W 60 V 28000 mAh) Gray',
    price: 27000,
    credit: 2700,
    cashback: 3000,
    model: 'TIGER X6',
    color: 'Gray',
    popularity: 87,
    manufacturer: 'Aima',
    imageUrl:
      'https://darwin.md/images/product/2021/06/darwin-scuter-electric-aima-tiger-x6-1800-w-60-v-28000-mah-gray-0.webp',
    type: 'personal-transport',
    segment: 'Scooter',
    link: 'aima-tiger-x6-1800w-motor-60v-28ah-gray',
    colors: ['gray', 'black'],
    releaseDate: 2021,
    supportedWeight: 180,
    wheelDiameter: 12,
    maxSpeed: 50,
    power: 1800,
    chargingTime: 8,
    batteryCapacity: 28000,
    electricRange: 60
  },
  {
    id: 4006,
    name: 'Electric Scooter AIMA TIGER X6 (1800 W 60 V 28000 mAh) Black',
    price: 27000,
    credit: 2700,
    cashback: 3000,
    model: 'TIGER X6',
    color: 'Black',
    popularity: 92,
    manufacturer: 'Aima',
    imageUrl:
      'https://darwin.md/images/product/2021/06/darwin-scuter-electric-aima-tiger-x6-1800-w-60-v-28000-mah-black-0.webp',
    type: 'personal-transport',
    segment: 'Scooter',
    link: 'aima-tiger-x6-1800w-motor-60v-28ah-black',
    colors: ['gray', 'black'],
    releaseDate: 2021,
    supportedWeight: 180,
    wheelDiameter: 12,
    maxSpeed: 50,
    power: 1800,
    chargingTime: 8,
    batteryCapacity: 28000,
    electricRange: 60
  },
  {
    id: 4007,
    name: 'Electric Scooter AIMA POWER EAGLE (800 W 20000 mAh) Black',
    price: 17000,
    credit: 1700,
    cashback: 2000,
    model: 'POWER EAGLE',
    color: 'Black',
    popularity: 81,
    manufacturer: 'Aima',
    imageUrl:
      'https://darwin.md/images/product/2021/06/scuter-electric-aima-power-eagle-with-sn-800-w-20000-mah-black-0.webp',
    type: 'personal-transport',
    segment: 'Scooter',
    link: 'aima-power-eagle',
    colors: ['black'],
    releaseDate: 2021,
    supportedWeight: 115,
    wheelDiameter: 14,
    maxSpeed: 40,
    power: 800,
    chargingTime: 8,
    batteryCapacity: 20000,
    electricRange: 60
  },
  {
    id: 4008,
    name: 'Electric Scooter AIMA TIGER S5 (1200 W 20000 mAh) Red',
    price: 19000,
    credit: 1900,
    cashback: 2000,
    model: 'TIGER S5',
    color: 'Red',
    popularity: 84,
    manufacturer: 'Aima',
    imageUrl:
      'https://darwin.md/images/product/2021/06/darwin-scuter-electric-aima-tiger-s5-1200-w-20000-mah-red-0.webp',
    type: 'personal-transport',
    segment: 'Scooter',
    link: 'aima-tiger-s5-1200w-motor-72v-20ah-red',
    colors: ['black'],
    releaseDate: 2021,
    supportedWeight: 180,
    wheelDiameter: 12,
    maxSpeed: 45,
    power: 1200,
    brakeType: 'Disc',
    chargingTime: 8,
    batteryCapacity: 20000,
    electricRange: 60,
    dimensions: '1800 x 1200 x 900 mm'
  },
  {
    id: 4009,
    name: 'Bicycle Roadking Cruiser Mountain 350 W White',
    price: 18000,
    credit: 1800,
    cashback: 2000,
    model: 'Cruiser Mountain',
    color: 'White',
    popularity: 85,
    manufacturer: 'RoadKing',
    imageUrl:
      'https://darwin.md/images/product/2021/06/darwin-bicicleta-electrica-cruiser-mountain-roadking-white-027.webp',
    type: 'personal-transport',
    segment: 'Mountain Bike',
    link: 'cruiser-mountain-roadking-white',
    colors: ['white'],
    releaseDate: 2021,
    weight: 27000,
    supportedWeight: 110,
    wheelDiameter: 26,
    maxSpeed: 40,
    power: 1200,
    brakeType: 'Disc (mecanic)',
    chargingTime: 6,
    batteryCapacity: 7800,
    electricRange: 40,
    gears: 7,
    frameMaterial: 'aluminium',
    dimensions: '800 x 580 x 220 mm'
  }
];
