export const sportAndHealth = [
  {
    id: 3001,
    name: 'Greentest Eco 6, Black',
    price: 3000,
    credit: 300,
    cashback: 400,
    model: 'Eco 6',
    color: 'Black',
    weight: 90,
    popularity: 63,
    manufacturer: 'Greentest',
    imageUrl:
      'https://darwin.md/images/product/2020/08/greentest_anmez6_black_1.webp',
    type: 'sport-and-health',
    segment: 'Nanometer',
    link: 'greentest-eco-6-black',
    colors: ['black'],
    resolution: '320 x 240',
    displayType: 'TFT',
    touchScreen: true,
    workingTimeHours: 20,
    batteryCapacity: 720
  },
  {
    id: 3002,
    name: 'Xiaomi iHealth 2 Smart Blood Pressure Monitor (BPM1), White',
    price: 1800,
    credit: 180,
    cashback: 200,
    model: 'BPM1',
    color: 'White',
    weight: 350,
    popularity: 59,
    manufacturer: 'Xiaomi',
    imageUrl:
      'https://darwin.md/images/product/2021/03/ihealth_smart_blood_1.webp',
    type: 'sport-and-health',
    segment: 'Blood pressure measurement',
    link: 'xiaomi-ihealth-2-smart-blood-pressure-monitor',
    colors: ['white'],
    resolution: '320 x 320',
    displayType: 'TFT',
    touchScreen: true,
    batteryCapacity: 2200,
    material: 'plastic'
  },
  {
    id: 3003,
    name: 'Glucometer iHealth Align, White',
    price: 500,
    credit: 50,
    cashback: 50,
    model: 'BG1',
    color: 'White',
    weight: 30,
    popularity: 57,
    manufacturer: 'iHealth',
    imageUrl:
      'https://darwin.md/images/product/2021/03/ihealth_glucometr_col_1.webp',
    type: 'sport-and-health',
    segment: 'Glucometer',
    link: 'ihealth-align-white',
    colors: ['white']
  },
  {
    id: 3004,
    name: 'Trimmer Moser 1400, Bordeaux',
    price: 850,
    credit: 85,
    cashback: 100,
    color: 'Bordeaux',
    weight: 90,
    popularity: 52,
    manufacturer: '	Moser',
    imageUrl: '/images/moser-1400.png',
    type: 'sport-and-health',
    segment: 'Trimmer',
    link: 'moser-1400-bordeaux',
    colors: [{ bordeaux: '#550A21' }],
    power: 10
  },
  {
    id: 3005,
    name: 'Xiaomi Walking Machine R1 Pro, Silver Gray',
    price: 10000,
    credit: 1000,
    cashback: 1000,
    model: 'Walking Machine R1 Pro',
    color: 'Gray',
    weight: 3300,
    popularity: 65,
    manufacturer: 'Xiaomi',
    imageUrl:
      'https://darwin.md/images/product/2021/09/xiaomi_walking_machine_r1_pro_black_5.webp',
    type: 'sport-and-health',
    segment: 'Walking Machine',
    link: 'xiaomi-walking-machine-r1-pro-silver-gray',
    colors: ['gray'],
    power: 918,
    material: 'metal',
    supportedWeight: 110,
    maxSpeed: 10
  },
  {
    id: 3006,
    name: 'Toothbrush Xiaomi Oclean F1 Light Blue',
    price: 450,
    credit: 45,
    cashback: 50,
    model: 'Oclean F1',
    color: 'LightBlue',
    weight: 98,
    popularity: 64,
    manufacturer: 'Greentest',
    imageUrl: '/images/oclean-f1-light-blue.webp',
    type: 'sport-and-health',
    segment: 'Toothbrush',
    link: 'xiaomi-oclean-f1-light-blue',
    colors: ['lightblue'],
    chargingTime: 2,
    workingTimeHours: 2
  },
  {
    id: 3007,
    name: 'Infrared Thermometer Berrcom JXB-178, White',
    price: 450,
    credit: 45,
    cashback: 50,
    model: 'JXB-178',
    color: 'White',
    weight: 90,
    popularity: 61,
    manufacturer: 'Greentest',
    imageUrl:
      'https://darwin.md/images/product/2020/09/berrcom_jxb_178_white_1.webp',
    type: 'sport-and-health',
    segment: 'Infrared Thermometer',
    link: 'infrared-non-contact-berrcom-jxb-178-white',
    colors: ['white'],
    batteryType: '2 x AA',
    errorRange: '±0.3 °C',
    measurementLevel: '32 - 43 °C'
  },
  {
    id: 3008,
    name: 'Hairdryer Rowenta CV5912F0, Black',
    price: 500,
    credit: 50,
    cashback: 50,
    model: 'CV5912F0',
    color: 'Black',
    popularity: 53,
    manufacturer: 'Rowenta',
    imageUrl:
      'https://darwin.md/images/product/2020/12/rowenta_cv_5912f0_1.webp',
    type: 'sport-and-health',
    segment: 'Hairdryer',
    link: 'rowenta-cv5912f0-black',
    colors: ['black'],
    power: 2300,
    wireLength: 1.8,
    coldAir: true,
    temperatureLevels: 3,
    gears: 2
  },
  {
    id: 3009,
    name: 'Weighing Vitek VT-8057, Orange',
    price: 200,
    model: 'VT-8057',
    color: 'Orange',
    popularity: 57,
    manufacturer: 'Vitek',
    imageUrl:
      'https://darwin.md/images/product/2021/03/vitek_vt_8057_orange_1.webp',
    type: 'sport-and-health',
    segment: 'Weighing',
    link: 'vitek-vt-8057-orange',
    colors: [{ orange: '#FD6600' }],
    supportedWeight: 180,
    batteryType: '1х CR2032',
    errorRange: '100g',
    dimensions: '26 x 26 cm'
  },
  {
    id: 3010,
    name: 'Hairdryer Polaris PHD1464T, Black',
    price: 250,
    model: 'PHD1464T',
    color: 'Black',
    weight: 236,
    popularity: 22,
    manufacturer: 'Polaris',
    imageUrl: 'https://darwin.md/images/product/2020/05/PHD1464T-1.webp',
    type: 'sport-and-health',
    segment: 'Hairdryer',
    link: 'hair-dryer-polaris-phd1464t-black',
    colors: ['black'],
    power: 1400,
    wireLength: 1.7,
    coldAir: true,
    gears: 2,
    material: 'plastic'
  },
  {
    id: 3011,
    name: 'Weighing Gorenje OT150LBW, White',
    price: 350,
    credit: 35,
    cashback: 50,
    model: 'OT150LBW',
    color: 'White',
    weight: 1500,
    popularity: 16,
    manufacturer: 'Gorenje',
    imageUrl:
      'https://darwin.md/images/product/2021/02/gorenje_ot150lbw_white_1.webp',
    type: 'sport-and-health',
    segment: 'Weighing',
    link: 'gorenje-ot150lbw-white',
    colors: ['white'],
    supportedWeight: 150,
    batteryType: '2х AAA',
    errorRange: '100g',
    dimensions: '32.6 x 33.5 x 4.4 cm'
  }
];
